export enum Questions {
  SHORT_ANSWER = 'SHORT_ANSWER',
  PARAGRAPH = 'PARAGRAPH',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CHECKBOXES = 'CHECKBOXES',
  DROP_DOWN = 'DROP-DOWN',
  FILE_UPLOAD = 'FILE_UPLOAD',
  DATE = 'DATE',
}
