name: Deploy to Production

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          SECRET_KEY: test-secret-key
          JWT_SECRET: test-jwt-secret

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          SECRET_KEY: test-secret-key
          JWT_SECRET: test-jwt-secret

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build -t google-forms-backend .

    # Add deployment steps here based on your preferred platform
    # Examples for different platforms:

    # For Heroku:
    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.14
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
    #     heroku_email: ${{ secrets.HEROKU_EMAIL }}

    # For Railway:
    # - name: Deploy to Railway
    #   uses: railway/cli@v1.0.0
    #   with:
    #     token: ${{ secrets.RAILWAY_TOKEN }}

    # For DigitalOcean App Platform:
    # - name: Deploy to DigitalOcean
    #   run: |
    #     doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
